# Generated by Django 3.2 on 2021-04-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Address',
            field=models.CharField(choices=[('2', '인천'), ('35', '경상북도'), ('1', '서울'), ('6', '부산'), ('33', '충청북도'), ('37', '전라북도'), ('31', '경기도'), ('36', '경상남도'), ('3', '대전'), ('5', '광주'), ('32', '강원도'), ('34', '충청남도'), ('7', '울산'), ('38', '전라남도'), ('4', '대구'), ('39', '제주도'), ('8', '세종특별자치시')], max_length=10, verbose_name='주소'),
        ),
    ]
