# Generated by Django 3.2 on 2021-04-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('Name', models.CharField(max_length=10, verbose_name='이름')),
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='사용자')),
                ('PW', models.CharField(max_length=50, verbose_name='비밀번호')),
                ('Sex', models.CharField(max_length=10, verbose_name='성별')),
                ('Age', models.CharField(max_length=10, verbose_name='나이')),
                ('Phone', models.CharField(max_length=20, verbose_name='전화번호')),
                ('Address', models.CharField(choices=[('R14', '전라남도'), ('R04', '부산광역시'), ('R03', '인천광역시'), ('R07', '대전광역시'), ('R11', '충청북도'), ('R16', '제주특별자치도'), ('R06', '광주광역시'), ('R12', '충청남도'), ('R05', '울산광역시'), ('R02', '서울특별시'), ('R09', '경상북도'), ('R17', '세종특별자치시'), ('R13', '전라북도'), ('R10', '경상남도'), ('R01', '경기도'), ('R08', '대구광역시'), ('R15', '강원도')], max_length=10, verbose_name='주소')),
            ],
        ),
    ]
