# Generated by Django 3.2 on 2021-04-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_auto_20210415_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Address',
            field=models.CharField(choices=[('R03', '인천광역시'), ('R10', '경상남도'), ('R05', '울산광역시'), ('R11', '충청북도'), ('R02', '서울특별시'), ('R09', '경상북도'), ('R06', '광주광역시'), ('R04', '부산광역시'), ('R17', '세종특별자치시'), ('R14', '전라남도'), ('R08', '대구광역시'), ('R12', '충청남도'), ('R07', '대전광역시'), ('R15', '강원도'), ('R13', '전라북도'), ('R01', '경기도'), ('R16', '제주특별자치도')], max_length=10, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Age',
            field=models.CharField(choices=[('A06', '60대+'), ('A03', '30대'), ('A05', '50대'), ('A04', '40대'), ('A01', '10대'), ('A02', '20대')], max_length=10, verbose_name='나이'),
        ),
    ]
