# Generated by Django 3.2 on 2021-04-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_auto_20210415_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season', models.CharField(max_length=10, verbose_name='계절')),
                ('Partner', models.CharField(max_length=10, verbose_name='파트너')),
                ('Theme', models.CharField(max_length=10, verbose_name='테마')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='Address',
            field=models.CharField(choices=[('R10', '경상남도'), ('R12', '충청남도'), ('R05', '울산광역시'), ('R07', '대전광역시'), ('R14', '전라남도'), ('R13', '전라북도'), ('R15', '강원도'), ('R11', '충청북도'), ('R16', '제주특별자치도'), ('R02', '서울특별시'), ('R08', '대구광역시'), ('R04', '부산광역시'), ('R17', '세종특별자치시'), ('R09', '경상북도'), ('R06', '광주광역시'), ('R03', '인천광역시'), ('R01', '경기도')], max_length=10, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Age',
            field=models.CharField(choices=[('A04', '40대'), ('A03', '30대'), ('A02', '20대'), ('A05', '50대'), ('A01', '10대'), ('A06', '60대+')], max_length=10, verbose_name='나이'),
        ),
    ]
