# Generated by Django 3.2 on 2021-04-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0006_auto_20210416_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='Theme',
            field=models.CharField(choices=[('T04', '체험관광지'), ('T10', '맛집'), ('T09', '쇼핑'), ('T06', '축제'), ('T01', '자연관광지'), ('T02', '역사관광지'), ('T11', '숙박'), ('T05', '문화시설'), ('T07', '공연/행사'), ('T08', '레포츠'), ('T03', '휴양관광지')], max_length=10, verbose_name='테마'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Address',
            field=models.CharField(choices=[('R10', '경상남도'), ('R08', '대구광역시'), ('R03', '인천광역시'), ('R17', '세종특별자치시'), ('R14', '전라남도'), ('R13', '전라북도'), ('R16', '제주특별자치도'), ('R01', '경기도'), ('R11', '충청북도'), ('R06', '광주광역시'), ('R15', '강원도'), ('R04', '부산광역시'), ('R07', '대전광역시'), ('R09', '경상북도'), ('R12', '충청남도'), ('R02', '서울특별시'), ('R05', '울산광역시')], max_length=10, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Age',
            field=models.CharField(choices=[('A02', '20대'), ('A01', '10대'), ('A05', '50대'), ('A06', '60대+'), ('A03', '30대'), ('A04', '40대')], max_length=10, verbose_name='나이'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Sex',
            field=models.CharField(choices=[('S01', '남자'), ('S02', '여자')], max_length=10, verbose_name='성별'),
        ),
    ]
