# Generated by Django 3.2 on 2021-04-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0007_auto_20210416_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='survey',
            name='Theme',
            field=models.CharField(choices=[('T07', '공연/행사'), ('T10', '맛집'), ('T11', '숙박'), ('T04', '체험관광지'), ('T01', '자연관광지'), ('T08', '레포츠'), ('T03', '휴양관광지'), ('T05', '문화시설'), ('T09', '쇼핑'), ('T06', '축제'), ('T02', '역사관광지')], max_length=10, verbose_name='테마'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Address',
            field=models.CharField(choices=[('R13', '전라북도'), ('R05', '울산광역시'), ('R08', '대구광역시'), ('R03', '인천광역시'), ('R16', '제주특별자치도'), ('R01', '경기도'), ('R09', '경상북도'), ('R14', '전라남도'), ('R17', '세종특별자치시'), ('R07', '대전광역시'), ('R10', '경상남도'), ('R04', '부산광역시'), ('R12', '충청남도'), ('R06', '광주광역시'), ('R11', '충청북도'), ('R02', '서울특별시'), ('R15', '강원도')], max_length=10, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Age',
            field=models.CharField(choices=[('A06', '60대+'), ('A04', '40대'), ('A05', '50대'), ('A02', '20대'), ('A01', '10대'), ('A03', '30대')], max_length=10, verbose_name='나이'),
        ),
    ]
