# Generated by Django 3.2 on 2021-04-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('Name', models.CharField(max_length=10, verbose_name='이름')),
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='아이디')),
                ('PW', models.CharField(max_length=50, verbose_name='비밀번호')),
                ('Sex', models.CharField(choices=[('S01', '남자'), ('S02', '여자')], max_length=10, verbose_name='성별')),
                ('Age', models.CharField(choices=[('G10', '10대'), ('G30', '30대'), ('G20', '20대'), ('G50', '50대'), ('G40', '40대'), ('G60', '60대+')], max_length=10, verbose_name='나이')),
                ('Phone', models.CharField(max_length=20, verbose_name='전화번호')),
                ('Address', models.CharField(choices=[('7', '울산'), ('3', '대전'), ('32', '강원도'), ('2', '인천'), ('31', '경기도'), ('37', '전라북도'), ('4', '대구'), ('1', '서울'), ('35', '경상북도'), ('5', '광주'), ('33', '충청북도'), ('38', '전라남도'), ('6', '부산'), ('8', '세종특별자치시'), ('39', '제주도'), ('34', '충청남도'), ('36', '경상남도')], max_length=10, verbose_name='주소')),
            ],
        ),
        migrations.AlterField(
            model_name='survey',
            name='Theme',
            field=models.CharField(choices=[('A02', '휴양관광지'), ('A02', '문화시설'), ('A05', '맛집'), ('A02', '역사관광지'), ('A01', '자연관광지'), ('A04', '쇼핑'), ('A02', '축제'), ('A02', '체험관광지'), ('A03', '레포츠'), ('B02', '숙박'), ('A02', '공연/행사')], max_length=10, verbose_name='테마'),
        ),
    ]
