# Generated by Django 3.2 on 2021-04-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Address',
            field=models.CharField(choices=[('R04', '부산광역시'), ('R10', '경상남도'), ('R15', '강원도'), ('R01', '경기도'), ('R09', '경상북도'), ('R02', '서울특별시'), ('R17', '세종특별자치시'), ('R03', '인천광역시'), ('R12', '충청남도'), ('R08', '대구광역시'), ('R11', '충청북도'), ('R06', '광주광역시'), ('R16', '제주특별자치도'), ('R13', '전라북도'), ('R14', '전라남도'), ('R07', '대전광역시'), ('R05', '울산광역시')], max_length=10, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Age',
            field=models.CharField(choices=[('A01', '10대'), ('A04', '40대'), ('A02', '20대'), ('A05', '50대'), ('A06', '60대+'), ('A03', '30대')], max_length=10, verbose_name='나이'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='아이디'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Sex',
            field=models.CharField(choices=[('S02', '여자'), ('S01', '남자')], max_length=10, verbose_name='성별'),
        ),
    ]
