# Generated by Django 3.2 on 2021-04-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_auto_20210415_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Address',
            field=models.CharField(choices=[('R05', '울산광역시'), ('R01', '경기도'), ('R17', '세종특별자치시'), ('R13', '전라북도'), ('R04', '부산광역시'), ('R12', '충청남도'), ('R09', '경상북도'), ('R02', '서울특별시'), ('R15', '강원도'), ('R07', '대전광역시'), ('R16', '제주특별자치도'), ('R14', '전라남도'), ('R03', '인천광역시'), ('R06', '광주광역시'), ('R08', '대구광역시'), ('R11', '충청북도'), ('R10', '경상남도')], max_length=10, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Age',
            field=models.CharField(choices=[('A05', '50대'), ('A04', '40대'), ('A03', '30대'), ('A06', '60대+'), ('A02', '20대'), ('A01', '10대')], max_length=10, verbose_name='나이'),
        ),
    ]
