# Generated by Django 3.2 on 2021-04-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mail', models.CharField(max_length=10, verbose_name='아이디')),
                ('Theme', models.CharField(max_length=10, verbose_name='테마')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Name', models.CharField(max_length=10, verbose_name='이름')),
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='아이디')),
                ('PW', models.CharField(max_length=50, verbose_name='비밀번호')),
                ('Sex', models.CharField(choices=[('S02', '여자'), ('S01', '남자')], max_length=10, verbose_name='성별')),
                ('Age', models.CharField(max_length=10, verbose_name='나이')),
                ('Phone', models.CharField(max_length=20, verbose_name='전화번호')),
                ('Address', models.CharField(choices=[('38', '전라남도'), ('33', '충청북도'), ('1', '서울'), ('5', '광주'), ('3', '대전'), ('32', '강원도'), ('39', '제주도'), ('31', '경기도'), ('7', '울산'), ('35', '경상북도'), ('4', '대구'), ('8', '세종특별자치시'), ('34', '충청남도'), ('36', '경상남도'), ('6', '부산'), ('2', '인천'), ('37', '전라북도')], max_length=10, verbose_name='주소')),
            ],
        ),
    ]
