# Generated by Django 3.2 on 2021-04-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0002_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='Mail',
            field=models.CharField(max_length=10, null=True, verbose_name='아이디'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Address',
            field=models.CharField(choices=[('38', '전라남도'), ('1', '서울'), ('32', '강원도'), ('37', '전라북도'), ('33', '충청북도'), ('5', '광주'), ('2', '인천'), ('8', '세종특별자치시'), ('31', '경기도'), ('34', '충청남도'), ('3', '대전'), ('4', '대구'), ('35', '경상북도'), ('39', '제주도'), ('36', '경상남도'), ('7', '울산'), ('6', '부산')], max_length=10, verbose_name='주소'),
        ),
    ]
