# Generated by Django 3.2 on 2021-04-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season', models.CharField(max_length=10, verbose_name='계절')),
                ('Partner', models.CharField(max_length=10, verbose_name='파트너')),
                ('Theme', models.CharField(choices=[('A01', '자연관광지'), ('A02', '공연/행사'), ('A02', '문화시설'), ('A03', '레포츠'), ('A04', '쇼핑'), ('A02', '축제'), ('A02', '체험관광지'), ('B02', '숙박'), ('A05', '맛집'), ('A02', '역사관광지'), ('A02', '휴양관광지')], max_length=10, verbose_name='테마')),
            ],
        ),
    ]
